#!/bin/bash
#
# stackdriver-agent-ctl - control stackdriver-agent for the gcp-tools-release
#
# Based on stackdriver-agent from Stackdriver package
# http://www.stackdriver.com
#
# Based on collectd.init from Debian package
# Copyright (C) 2005-2006 Florian Forster <octo@verplant.org>
# Copyright (C) 2006-2009 Sebastian Harl <tokkee@debian.org>
#

### BEGIN INIT INFO
# Provides:          stackdriver-agent
# Required-Start:    $local_fs $remote_fs
# Required-Stop:     $local_fs $remote_fs
# Should-Start:      $network $named $syslog $time cpufrequtils
# Should-Stop:       $network $named $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: start and stop Stackdriver Agent
# Description: The Stackdriver Agent is used with the Stackdriver monitoring SaaS service.
### END INIT INFO

RUN_DIR=/var/vcap/sys/run/stackdriver_agent
LOG_DIR=/var/vcap/sys/log/stackdriver_agent
PKG_DIR=/var/vcap/packages/stackdriver-agent
JOB_DIR=/var/vcap/jobs/stackdriver_agent
DETECT_GCM="yes"

export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:${PKG_DIR}/libtool/lib:${PKG_DIR}/libyajl/lib"

source ${PKG_DIR}/utils.sh

. /lib/lsb/init-functions

export PATH=/sbin:/bin:/usr/sbin:/usr/bin

DISABLE=0

DESC="Stackdriver metrics collection agent"
NAME=stackdriver-agent
DAEMON=${PKG_DIR}/collectd/sbin/stackdriver-collectd

CONFIGFILE=${JOB_DIR}/config/collectd.conf
CONFIG_TEMPLATE=${JOB_DIR}/config/collectd.conf.tmpl
GCM_CONFIG_TEMPLATE=${JOB_DIR}/config/collectd-gcm.conf.tmpl
_PIDFILE=${RUN_DIR}/stackdriver_collectd.pid


MAXWAIT=30

JAVA_LIB_DIR=""

# Gracefully exit if the package has been removed.
test -x $DAEMON || exit 0

if [ -r /etc/default/${NAME} ]; then
    . /etc/default/${NAME}
fi

if test "$ENABLE_COREFILES" == 1; then
    ulimit -c unlimited
fi

# Attempt to discover the location of the Java libraries.
find_libjvm_so () {
    local java_lib_dir
    local java_home=$(dirname "$(readlink -f "$(bash -lc "which java 2>/dev/null")")")/..
    [ "$java_home" = "./.." ] && return
    local lib_subdirs=("lib/amd64/server" "lib/x64/server" "lib/i386/server")
    local lib_subdirs_with_jre=()
    for subdir in "${lib_subdirs[@]}"; do
        lib_subdirs_with_jre+=("$subdir" "jre/$subdir")
    done
    for libdir in "${lib_subdirs_with_jre[@]/#/$java_home/}"; do
        if [ -f "$libdir/libjvm.so" ]; then
            java_lib_dir="$libdir"
            break
        fi
    done
    echo $java_lib_dir
}

[ -n "$JAVA_LIB_DIR" ] || JAVA_LIB_DIR=$(find_libjvm_so)
if [ -n "$JAVA_LIB_DIR" ]; then
    export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$JAVA_LIB_DIR"
fi

get_instance_id () {
    local iid

    # allow override of instance id in sysconfig file
    if [ -n "$INSTANCE_ID" ]; then
        iid=$INSTANCE_ID
    elif [ -r /opt/stackdriver/hostid ]; then
        iid=$(cat /opt/stackdriver/hostid)
    # RS: Check Rackspace first because we can fail quickly.
    elif [[ -x /usr/bin/xenstore-read && $(/usr/bin/xenstore-read vm-data/provider_data/provider) = "Rackspace" ]]; then
        iid=$(/usr/bin/xenstore-read name |sed -e 's/^instance-//')
    elif [ -z "$SKIP_METADATA_CHECKS" ]; then
        # AWS: If we're on EC2, this ought to return the instance id.
        iid=$(curl --silent -f http://169.254.169.254/latest/meta-data/instance-id 2>/dev/null)
        if [ -z "$iid" ]; then
            # that failed.  let's try to see if it looks like we're on GCE
            iid=$(curl --silent -f -H 'Metadata-Flavor: Google' http://169.254.169.254/computeMetadata/v1/instance/id 2>/dev/null)
        fi
    elif [ -r /sys/hypervisor/uuid -a $(cat /sys/hypervisor/version/extra |grep -c amazon) -eq 0 ]; then
        iid=$(cat /sys/hypervisor/uuid)
    else
        echo 'Unable to discover an id for this machine!' >&2
    fi

    echo $iid
}

get_collectd_endpoint () {
    for endpoint in collectd-gateway.google.stackdriver.com collectd-gateway.stackdriver.com; do
        if [[ "200" = $(curl --silent -f -s -w "%{http_code}" --retry 1 -o /dev/null https://${endpoint}/v1/agent-test?stackdriver-apikey=${STACKDRIVER_API_KEY} 2>/dev/null) ]]; then
            echo $endpoint
            return
        fi
    done
    echo 'Unable to determine collectd endpoint!' >&2
    return 1
}

gen_hostid() {
    echo "Generating a host id"
    uuidgen > /opt/stackdriver/hostid
    return 0
}

gen_config() {
    if [ "$AUTOGENERATE_COLLECTD_CONFIG" = "no" ]; then
        return
    fi
    AUTOGENERATE_HEADER="# NOTE: This file is auto-generated and will be overwritten unless you set
#     AUTOGENERATE_COLLECTD_CONFIG=\"no\"
# in /etc/default/$NAME
"
    if [ -z "$USE_GCM_API" -a -n "$DETECT_GCM" ]; then
        # automatically determine if we should be using the GCM API
        # first, see if the instance has a monitoring.write scope
        INSTANCE_SCOPES=$(curl --silent -f -H "Metadata-Flavor: Google" http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/scopes 2>/dev/null)$'\n'
        if [[ $INSTANCE_SCOPES == *"/monitoring.write"$'\n'* || $INSTANCE_SCOPES == *"/monitoring"$'\n'* || $INSTANCE_SCOPES == *"/cloud-platform"$'\n'* ]]; then
            log_progress_msg "Found sufficient authorization scope for the GCM API"
            USE_GCM_API="yes"
        # second, see if the application default credential file is in the system location
        elif [ -f /etc/google/auth/application_default_credentials.json ]; then
            log_progress_msg "Found a credentials file"
            USE_GCM_API="yes"
        else
            log_warning_msg "Not authorized to talk to the GCM API, falling back on legacy"
            USE_GCM_API="no"
        fi
    fi
    # now see if we should be using write_gcm and use the appropriate template if so
    if [ "$USE_GCM_API" = "yes" ]; then
        echo "$AUTOGENERATE_HEADER" > $CONFIGFILE
        cat $GCM_CONFIG_TEMPLATE >> $CONFIGFILE
        return
    fi

    if test -z "$STACKDRIVER_API_KEY" ; then
        STACKDRIVER_API_KEY=$(curl --silent -f -H "Metadata-Flavor: Google" http://169.254.169.254/computeMetadata/v1/project/attributes/stackdriver-agent-key 2>/dev/null)
        if test -z "$STACKDRIVER_API_KEY"; then
            log_failure_msg "Need to set STACKDRIVER_API_KEY in /etc/default/$NAME"
            return 3
        fi
    fi

    local IID=$(get_instance_id)
    if [ -z "$IID" ]; then
        log_failure_msg "Unable to discover instance id"
        return
    fi
    if [ -z "$COLLECTD_ENDPOINT"]; then
        COLLECTD_ENDPOINT=$(get_collectd_endpoint)
        if [[ $? -ne 0 ]]; then
            return 1
        fi
    fi
    echo "$AUTOGENERATE_HEADER" > $CONFIGFILE
    sed -e "s/{IID}/$IID/; s/{API_KEY}/$STACKDRIVER_API_KEY/; s|{COLLECTD_ENDPOINT}|$COLLECTD_ENDPOINT|" $CONFIG_TEMPLATE >> $CONFIGFILE
}

# return:
#   0 if config is fine
#   1 if there is a syntax error
#   2 if there is no configuration
check_config() {
    if test ! -e "$CONFIGFILE"; then
        return 2
    fi
    if ! $DAEMON -t -C "$CONFIGFILE"; then
        return 1
    fi
    return 0
}

# return:
#   0 if the daemon has been started
#   1 if the daemon was already running
#   2 if the daemon could not be started
#   3 if the daemon was not supposed to be started
d_start() {
    if test "$DISABLE" != 0; then
        # we get here during restart
        log_progress_msg "disabled by /etc/default/$NAME"
        return 3
    fi

    GOOGLE_MONITORING_ENABLE=$(curl --silent -f -H "Metadata-Flavor: Google" http://169.254.169.254/computeMetadata/v1/instance/attributes/google-monitoring-enable 2>/dev/null)
    if [ -n "$GOOGLE_MONITORING_ENABLE" -a "$GOOGLE_MONITORING_ENABLE" = "0" ]; then
        log_warning_msg "Disabled via metadata"
        return 3
    fi

    # allow setting a proxy
    if [ -n "$PROXY_URL" ]; then
        export https_proxy=$PROXY_URL
    fi

    if ! gen_config || ! check_config; then
        log_failure_msg "not starting, configuration error"
        return 3
    fi

    if test "$USE_COLLECTDMON" == 1; then
        LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/opt/stackdriver/collectd/lib64:/opt/stackdriver/collectd/lib" start-stop-daemon --start --quiet --oknodo --pidfile "$_PIDFILE" \
            --exec $COLLECTDMON_DAEMON -- -P "$_PIDFILE" -- -C "$CONFIGFILE" \
            || return 2
    else
        LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/opt/stackdriver/collectd/lib64:/opt/stackdriver/collectd/lib" start-stop-daemon --start --quiet --oknodo --pidfile "$_PIDFILE" \
            --exec $DAEMON -- -C "$CONFIGFILE" -P "$_PIDFILE" \
            || return 2
    fi
    return 0
}

still_running_warning="
WARNING: $NAME might still be running.
In large setups it might take some time to write all pending data to
the disk. You can adjust the waiting time in /etc/default/$NAME."

# return:
#   0 if the daemon has been stopped
#   1 if the daemon was already stopped
#   2 if daemon could not be stopped
d_stop() {
    PID=$( cat "$_PIDFILE" 2> /dev/null ) || true

    start-stop-daemon --stop --quiet --oknodo --pidfile "$_PIDFILE"
    rc="$?"

    if test "$rc" -eq 2; then
        return 2
    fi

    sleep 1
    if test -n "$PID" && kill -0 $PID 2> /dev/null; then
        i=0
        while kill -0 $PID 2> /dev/null; do
            i=$(( $i + 2 ))
            echo -n " ."

            if test $i -gt $MAXWAIT; then
                log_progress_msg "$still_running_warning"
                return 2
            fi

            sleep 2
        done
        return "$rc"
    fi
    return "$rc"
}

case "$1" in
    start)
        log_daemon_msg "Starting $DESC" "$NAME"
        d_start
        case "$?" in
            0|1) log_end_msg 0 ;;
            2) log_end_msg 1 ;;
            3) log_end_msg 255; true ;;
            *) log_end_msg 1 ;;
        esac
        ;;
    stop)
        log_daemon_msg "Stopping $DESC" "$NAME"
        d_stop
        case "$?" in
            0|1) log_end_msg 0 ;;
            2) log_end_msg 1 ;;
        esac
        ;;
    status)
        status_of_proc -p "$_PIDFILE" "$DAEMON" "$NAME" && exit 0 || exit $?
        ;;
    restart|force-reload)
        log_daemon_msg "Restarting $DESC" "$NAME"
        check_config
        rc="$?"
        if test "$rc" -eq 1; then
            log_progress_msg "not restarting, configuration error"
            log_end_msg 1
            exit 1
        fi
        d_stop
        rc="$?"
        case "$rc" in
            0|1)
                sleep 1
                d_start
                rc2="$?"
                case "$rc2" in
                    0|1) log_end_msg 0 ;;
                    2) log_end_msg 1 ;;
                    3) log_end_msg 255; true ;;
                    *) log_end_msg 1 ;;
                esac
                ;;
            *)
                log_end_msg 1
                ;;
        esac
        ;;
    genhostid)
        gen_hostid
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|force-reload|status}" >&2
        exit 3
        ;;
esac

# vim: syntax=sh noexpandtab sw=4 ts=4 :
